// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Servicio_WCF.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Servicio_WCF.Models
{
    public partial interface IDBDigitalBankstContextProcedures
    {
        Task<int> ActualizarAsync(int? Id, string Nombre, DateTime? FechaNacimiento, string Sexo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AgregarAsync(string Nombre, DateTime? FechaNacimiento, string Sexo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> EliminarAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerResult>> ObtenerAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
