// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Servicio_WCF.Models
{
    public partial class Sexo
    {
        public Sexo()
        {
            Usuario = new HashSet<Usuario>();
        }

        public string Nombre { get; set; }

        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}